# Generated by Django 2.0.2 on 2018-02-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('country_slug', models.CharField(max_length=250)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='')),
                ('sport', models.ManyToManyField(to='sports.Sport')),
            ],
        ),
    ]
