# Generated by Django 2.0.2 on 2018-02-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_data',
            name='sport',
        ),
    ]
