# Generated by Django 2.0.2 on 2018-02-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('nations', '0002_remove_country_data_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_data',
            name='sport',
            field=models.ManyToManyField(to='sports.Sport'),
        ),
        migrations.AlterField(
            model_name='country_data',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
