# Generated by Django 2.0.2 on 2018-02-19 10:49

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headline_image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='post',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='teams.Team'),
        ),
    ]
